### ISSUE TITLE
Same content as last week for Swedish

### ISSUE THREAD

**Issue by Ainali** [hatnote/weeklypedia#65] opened 2022-06-10 18:38 UTC
Compare [20220603](https://weekly.hatnote.com/archive/sv/20220603/weeklypedia_20220603.html) and [20220610](https://weekly.hatnote.com/archive/sv/20220610/weeklypedia_20220610.html), the content is the same (even the dates are the same). The only thing that has changed is the issue number.

**Comment by mahmoud** [comment] 2022-06-16 07:11
Hey Jan! Thank you for the heads up. The last couple weeks have been hectic and I missed my alert. I just committed and deployed a fix, and this week's newsletter should be correct.

I've worked around the root cause, a toolforge OS upgrade, which does not seem to have installed MySQL client libraries. I let them know in IRC, but for now I ported weeklypedia over to a pure-python solution. 

If there's any issue this week, do let me know here and I'll work as fast as I can to resolve. Thanks again!

**Closed by mahmoud** 2022-06-16 07:11 UTC
